# Generated by the build-on-aws/terraform-samples/modules/bootstrap-aws-account module.
# While changes won't be overwritten unless run locally and committed, highly recommended
# to not change this outside of the module.
terraform {
  backend "s3" {
    bucket         = "aws-archangelo-terraform"
    key            = "terraform-state"
    region         = "ca-central-1"
    encrypt        = true
    kms_key_id     = "alias/aws/s3"
    dynamodb_table = "terraform-state-lock"
  }
}
