# Generated by the build-on-aws/terraform-samples/modules/bootstrap-aws-account module.
# While changes won't be overwritten unless run locally and committed, highly recommended
# to not change this outside of the module.
terraform {
  required_version = ">= 1.9.7"

  required_providers {
    aws = {
      source  = "hashicorp/aws"
      version = ">= 5.70.0"
    }
    local = {
      source  = "hashicorp/local"
      version = ">= 2.5.2"
    }
  }
}
